"""Race data for every Course Clock race page.

One entry per race. Only publish facts that trace to a source. When a number is
unknown, leave it as None and the page says "not listed" instead of guessing.

Dates are ISO strings (YYYY-MM-DD). d2027 is None until IRONMAN announces it.
Sources used for the October 2026 build: endurance.biz 2026 USA/Canada schedule,
RaceCenter race pages (2027 dates), Triathlete 2026 race guides, TRI247, TrainingPeaks,
local tourism boards and local news course guides. See README for the update process.
"""

H = 3600
STANDARD_CUTOFFS = {
    "full": {"swim": 140 * 60, "bike": 10.5 * H, "total": 17 * H},
    "half": {"swim": 70 * 60, "bike": 5.5 * H, "total": 8.5 * H},
}
STANDARD_NOTE = {
    "full": "Cutoffs shown are the standard IRONMAN limits (2:20 swim, 10:30 swim through bike, 17:00 total, all from your own start). Check this year's athlete guide.",
    "half": "Cutoffs shown are the standard IRONMAN 70.3 limits (1:10 swim, 5:30 swim through bike, 8:30 total, all from your own start). Check this year's athlete guide.",
}
DISTANCES = {"full": (2.4, 112, 26.2), "half": (1.2, 56, 13.1)}

REGIONS = {
    "Southeast": {"TN", "NC", "GA", "FL"},
    "Texas": {"TX"},
    "Northeast": {"NY", "MD", "PA", "MA", "ME"},
    "Midwest": {"WI", "OH", "MI", "IN", "IL", "NE", "KY"},
    "West": {"CA", "CO", "ID", "OR", "WA", "NM", "HI"},
}


def race(slug, name, city, state, dist, d2026, d2027, swim, bike, run, *,
         swimMi=None, swimFactor=1, bikeGainFt=None, runGainFt=None,
         bikeTerrain=None, runTerrain=None, weather=None, cutoffs=None,
         cutoffNote=None, note=None, short=None, d2027_label=None):
    s, b, r = DISTANCES[dist]
    region = next(k for k, v in REGIONS.items() if state in v)
    return {
        "slug": slug, "name": name, "city": city, "state": state, "region": region,
        "place": f"{city}, {STATE_NAMES[state]}", "dist": dist,
        "swimMi": swimMi or s, "bikeMi": b, "runMi": r,
        "d2026": d2026, "d2027": d2027, "d2027_label": d2027_label,
        "bikeGainFt": bikeGainFt, "runGainFt": runGainFt,
        "bikeTerrain": bikeTerrain, "runTerrain": runTerrain,
        "swimFactor": swimFactor,
        "cutoffs": cutoffs or STANDARD_CUTOFFS[dist],
        "cutoffNote": cutoffNote or STANDARD_NOTE[dist],
        "legs": {"Swim": swim, "Bike": bike, "Run": run},
        "weather": weather, "note": note, "short": short or name.replace("IRONMAN ", ""),
    }


STATE_NAMES = {
    "TN": "Tennessee", "NC": "North Carolina", "GA": "Georgia", "FL": "Florida", "TX": "Texas",
    "NY": "New York", "MD": "Maryland", "PA": "Pennsylvania", "MA": "Massachusetts", "ME": "Maine",
    "WI": "Wisconsin", "OH": "Ohio", "MI": "Michigan", "IN": "Indiana", "IL": "Illinois",
    "NE": "Nebraska", "KY": "Kentucky", "CA": "California", "CO": "Colorado", "ID": "Idaho",
    "OR": "Oregon", "WA": "Washington", "NM": "New Mexico", "HI": "Hawaii",
}

CHATT_70_3_SWIM = "Point to point, downriver in the Tennessee River to Ross's Landing. Listed at 1.4 miles in 2026 (1.2 miles in earlier years), with water usually in the low 70s F. The current helps, so the predictor takes 10% off your pace when course adjustments are on."
CHATT_70_3_BIKE = "One loop: about 11 miles south of town, then a loop in north Georgia past historic Chickamauga and along Lookout Mountain. Rolling, with about 2,218 ft of climbing."
CHATT_70_3_RUN = "Two loops through downtown, the Riverwalk, Veterans Bridge and the North Shore, finishing at Ross's Landing. About 550 ft of climbing. In 2026 a temporary detour skipped the Walnut Street Bridge."

RACES = [
    # ---------------- Full distance ----------------
    race("ironman-texas", "IRONMAN Texas", "The Woodlands", "TX", "full", "2026-04-18", "2027-04-24",
         "Point to point in Lake Woodlands. Water has hovered around 74 F, right on the edge of the wetsuit cutoff.",
         "Two loops on the Hardy Toll Road, mostly closed to traffic. Flat and fast, with a headwind one way, a tailwind the other, and no shade.",
         "Three loops around the lake and waterway. Flat, with the Hippie Hollow spectator section near mile 6.",
         bikeTerrain="Flat", runTerrain="Flat",
         weather="April heat and humidity. The bike has no shade, so start drinking early."),
    race("ironman-jacksonville", "IRONMAN Jacksonville", "Jacksonville", "FL", "full", "2026-05-16", "2027-05-16",
         "Point to point in the St. Johns River, timed with the incoming tide. Wetsuit legal, with water around 67 F.",
         "Two loops starting downtown, about 873 ft of climbing.",
         "Two loops through the city with river views and a crossing of the Main Street Bridge. Very flat, about 301 ft of climbing.",
         bikeGainFt=873, runGainFt=301,
         weather="Race day air temperatures have ranged from about 71 to 94 F. Plan for heat on the run."),
    race("ironman-lake-placid", "IRONMAN Lake Placid", "Lake Placid", "NY", "full", "2026-07-19", "2027-07-25",
         "Two loops in Mirror Lake, with an underwater cable a few feet down that makes sighting easy. Water usually high 60s to low 70s F.",
         "Two loops with about 7,432 ft of climbing, including the Keene descent, which drops about 1,500 ft over 4 to 5 miles. Pace the climbs back to town carefully.",
         "Two loops through town and out River Road, with Mill Hill on each lap. About 1,258 ft of climbing.",
         bikeGainFt=7432, runGainFt=1258,
         weather="Usually one of the first full IRONMANs in North America to sell out. Register early."),
    race("ironman-wisconsin", "IRONMAN Wisconsin", "Madison", "WI", "full", "2026-09-13", None,
         "Two loops in Lake Monona beside Monona Terrace. Athletes have voted it a favorite swim among IRONMAN races.",
         "Two loops through the farmland around Verona, Mount Horeb and Cross Plains. Hilly the whole way, with about 4,120 ft of climbing as published locally (GPS readings run higher). What you spend on loop one shows up on the run.",
         "Two loops past Lake Mendota, State Street and the field at Camp Randall Stadium, finishing just past the Capitol Square.",
         bikeGainFt=4120, runTerrain="Rolling"),
    race("ironman-maryland", "IRONMAN Maryland", "Cambridge", "MD", "full", "2026-09-19", None,
         "Two loops in the Choptank River at sunrise.",
         "Two loops through Blackwater National Wildlife Refuge. Virtually flat, so wind is the main challenge.",
         "Three loops through downtown Cambridge with strong spectator support.",
         bikeTerrain="Flat", runTerrain="Flat",
         weather="Water and wind conditions can change quickly here. Be ready for chop in the river and wind on the bike."),
    race("ironman-chattanooga", "IRONMAN Chattanooga", "Chattanooga", "TN", "full", "2026-09-27", None,
         "Point to point, downstream in the Tennessee River, finishing at Ross's Landing. The current usually makes this one of the faster IRONMAN swims, so the predictor takes 10% off your pace when course adjustments are on.",
         "Three laps on US-27 with fresh pavement and a dedicated bike lane, about 4,300 ft of climbing over 112 miles. Steady effort matters more than chasing speed on the climbs.",
         "Two loops through downtown, the Riverwalk, Veterans Bridge and the North Shore, about 1,150 ft of climbing. The North Shore hills come twice, so save something for the second loop.",
         swimFactor=0.9, bikeGainFt=4300, runGainFt=1150,
         cutoffs={"swim": None, "bike": 10 * H, "total": 16.5 * H},
         cutoffNote="Cutoffs shown are the last ones we could confirm (10 hours for swim, T1 and bike; 16:30 total from your own start). Check this year's athlete guide.",
         weather="Often hot and humid. Plan for heat on the run."),
    race("ironman-california", "IRONMAN California", "Sacramento", "CA", "full", "2026-10-18", None,
         "Point to point from the American River into the Sacramento River. Mild water and a fast course.",
         "Two loops, flat and fast through wine country. About 710 ft of climbing.",
         "Along river trails and the Capitol Mall. One of the flattest marathons on the IRONMAN circuit, about 426 ft of climbing.",
         bikeGainFt=710, runGainFt=426),
    race("ironman-florida", "IRONMAN Florida", "Panama City Beach", "FL", "full", "2026-11-07", None,
         "Two loops in the Gulf of Mexico around the Russell-Fields Pier. Clear water, but current and waves are unpredictable. Water has been around 78 F, too warm for wetsuits.",
         "Single loop along the intracoastal waterways into Pine Log State Forest and back. Mostly flat with some rollers, about 1,600 ft of climbing. Expect a headwind one way.",
         "Two loops past the beachfront hotels on Front Beach Road. Nearly flat, and your family can see you four times.",
         bikeGainFt=1600, runGainFt=100,
         weather="The longest running IRONMAN in North America. Gulf wind and chop are the variables to watch."),
    race("ironman-world-championship-kona", "IRONMAN World Championship", "Kailua-Kona", "HI", "full", "2026-10-10", "2027-10-09",
         "One loop in Kailua Bay in open ocean. Water is too warm for wetsuits.",
         "Out the Queen Kaahumanu Highway through the lava fields to Hawi and back. Crosswinds and heat are the defining challenges.",
         "Along Alii Drive, then out the Queen K and through the Natural Energy Lab, where there is no shade.",
         bikeTerrain="Rolling, windy", runTerrain="Rolling",
         weather="Entry is by qualification only. Expect heat, humidity and wind all day.",
         short="Kona World Championship"),

    # ---------------- 70.3 ----------------
    race("ironman-70-3-oceanside", "IRONMAN 70.3 Oceanside", "Oceanside", "CA", "half", "2026-03-28", "2027-04-03",
         "One lap in Oceanside Harbor, starting on the beach. Water is cold, around 60 F, so plan on a wetsuit.",
         "One loop through Camp Pendleton with San Mateo Hill and two other real climbs, about 2,625 ft in total. Usually windy on the way back into Oceanside.",
         "Two laps down The Strand and through seaside neighborhoods, finishing near the pier. Rolling, with short sharp climbs.",
         bikeGainFt=2625, runTerrain="Rolling"),
    race("ironman-70-3-texas", "IRONMAN 70.3 Texas", "Galveston", "TX", "half", "2026-03-29", "2027-04-04",
         "On the bay side of the island in relatively flat water. Usually in the mid 70s F and wetsuit legal, so a sleeveless suit helps.",
         "Straight out and back on flat roads, with one slight rise at San Luis Pass. Strong crosswinds are common, and flats are frequent, so carry a repair kit.",
         "Flat, multi-loop course on hard surfaces that passes transition often. Heat is the main challenge.",
         bikeTerrain="Flat, windy", runTerrain="Flat"),
    race("ironman-70-3-dallas-little-elm", "IRONMAN 70.3 Dallas-Little Elm", "Little Elm", "TX", "half", "2026-03-15", "2027-03-14",
         "One loop in Lewisville Lake at Little Elm Beach. March water usually runs 54 to 60 F, so wetsuits are expected.",
         "Gently rolling rural roads north of Little Elm with smooth pavement, about 1,400 ft of climbing.",
         "Three loops on hard-packed crushed gravel nature trails. Flat and fast.",
         bikeGainFt=1400, runTerrain="Flat", short="70.3 Dallas"),
    race("ironman-70-3-gulf-coast", "IRONMAN 70.3 Gulf Coast", "Panama City Beach", "FL", "half", "2026-05-09", "2027-05-08",
         "Open water swim in the Gulf of Mexico off Panama City Beach. Conditions range from calm to choppy year to year.",
         "Flat roads inland from the beach. Wind is the main variable.",
         "Flat course close to the beach.",
         bikeTerrain="Flat", runTerrain="Flat"),
    race("ironman-70-3-chattanooga", "IRONMAN 70.3 Chattanooga", "Chattanooga", "TN", "half", "2026-05-17", "2027-05-16",
         CHATT_70_3_SWIM, CHATT_70_3_BIKE, CHATT_70_3_RUN,
         swimMi=1.4, swimFactor=0.9, bikeGainFt=2218, runGainFt=550,
         cutoffs={"swim": None, "bike": 5.5 * H, "total": 8.5 * H},
         cutoffNote="Cutoffs shown are 5:30 for swim, T1 and bike and 8:30 total from your own start. Past guides also listed intermediate cutoffs on the bike and run. Check this year's athlete guide.",
         weather="Late spring heat is common. This is one of the most popular 70.3s in North America and it regularly sells out."),
    race("ironman-70-3-hawaii", "IRONMAN 70.3 Hawaii", "Kohala Coast", "HI", "half", "2026-05-30", "2027-06-05",
         "Pacific Ocean swim starting at Pauoa Bay. Water is around 75 F, so no wetsuits.",
         "The northern part of the World Championship course, including the climb to Hawi through lava fields. Exposed and often very windy.",
         "Two loops through the Mauna Lani golf course and lava fields. Temperatures reach the mid 80s F with high humidity.",
         bikeTerrain="Rolling, windy", runTerrain="Rolling",
         weather="Heat, humidity and wind make this one of the harder 70.3 courses."),
    race("ironman-70-3-omaha", "IRONMAN 70.3 Omaha", "Omaha", "NE", "half", "2026-06-07", "2027-06-06",
         "One lap at Lake Cunningham in northwest Omaha with a rolling start.",
         "Point to point from Lake Cunningham through northwest Omaha to downtown. Hillier than people expect, with about 2,921 ft of climbing.",
         "Two laps along the Missouri River on the Riverfront Trail, crossing the Bob Kerrey Pedestrian Bridge into Council Bluffs, Iowa, and back.",
         bikeGainFt=2921, runTerrain="Flat",
         weather="Nebraska's first IRONMAN event, which debuted in 2026."),
    race("ironman-70-3-western-massachusetts", "IRONMAN 70.3 Western Massachusetts", "Springfield", "MA", "half", "2026-06-07", None,
         "Lake swim outside Springfield. The venue has shifted since the race began, so confirm it in this year's athlete guide.",
         "Includes 10 to 15 miles through Suffield, Connecticut, on a route revised in 2024 for fewer turns and better road surfaces.",
         "Heads toward Forest Park by way of Log Hill and finishes on Court Street in downtown Springfield (2024 layout).",
         short="70.3 Western Mass"),
    race("ironman-70-3-boulder", "IRONMAN 70.3 Boulder", "Boulder", "CO", "half", "2026-06-13", "2027-06-12",
         "One counter-clockwise loop in Boulder Reservoir. Water often runs 70 to 74 F, which can mean no wetsuits. The sun is in your eyes on the way out, so bring dark goggles.",
         "One loop with no big climbs but plenty of rollers, so it is harder than it looks on paper.",
         "Two loops around the reservoir, about 90% on dirt road and trail, with about 197 ft of climbing. Expect to run 5 to 10 seconds per mile slower than on pavement.",
         runGainFt=197, bikeTerrain="Rolling",
         weather="Race site sits around 5,430 ft. The dry heat is usually a bigger problem than the altitude: you sweat more than you notice."),
    race("ironman-70-3-pennsylvania-happy-valley", "IRONMAN 70.3 Pennsylvania Happy Valley", "State College", "PA", "half", "2026-06-14", None,
         "One clockwise loop in Foster Joseph Sayers Reservoir at Bald Eagle State Park, starting and finishing at the beach.",
         "Point to point northeast through Mill Hall, Hublers Ridge, Pleasant Gap and Centre Hall, finishing near Beaver Stadium.",
         "Two loops through the Penn State campus past Old Main, finishing inside Beaver Stadium.",
         short="70.3 Happy Valley"),
    race("ironman-70-3-eagleman", "IRONMAN 70.3 Eagleman", "Cambridge", "MD", "half", "2026-06-14", "2027-06-13",
         "Open water swim in the Choptank River.",
         "Flat course through Blackwater National Wildlife Refuge. Good for holding a steady cadence, but exposed to wind.",
         "Flat 13.1 miles finishing at Gerry Boyle Park.",
         bikeTerrain="Flat", runTerrain="Flat",
         weather="Eagleman has a long history of hot, humid race days. Plan your hydration around heat."),
    race("ironman-70-3-rockford", "IRONMAN 70.3 Rockford", "Rockford", "IL", "half", "2026-06-14", None,
         "Starts at the Rock Guardians sculpture and heads south down the Rock River, exiting at 200 S. Wyman Street.",
         "One loop north through rural farmland and the village of Rockton. Gentle elevation changes on country roads.",
         "Two loops along both sides of the Rock River on park trails and greenways, finishing on North Main Street.",
         bikeTerrain="Gently rolling",
         weather="Rockford signed to host the race through 2027."),
    race("ironman-70-3-coeur-dalene", "IRONMAN 70.3 Coeur d'Alene", "Coeur d'Alene", "ID", "half", "2026-06-21", "2027-06-27",
         "Lake Coeur d'Alene. Early summer water in this lake is cold, so plan on a wetsuit.",
         "We could not verify the current bike route and climbing. Check this year's athlete guide.",
         "Finishes in downtown Coeur d'Alene near the lake. Check the athlete guide for the current route.",
         short="70.3 Coeur d'Alene"),
    race("ironman-70-3-muncie", "IRONMAN 70.3 Muncie", "Muncie", "IN", "half", "2026-07-11", "2027-07-10",
         "Clockwise swim that finishes at a beach. On a clear morning you swim into the sun at the end, so wear tinted goggles.",
         "Two loops. Early rollers and rough pavement, then US-35, where you can build speed despite headwinds.",
         "Out and back with steady hills and little shade. It never really gets easy, and there is a climb just before the last drop to the finish.",
         bikeTerrain="Rolling", runTerrain="Hilly",
         weather="Expect hot, humid weather and the chance of wind or storms."),
    race("ironman-70-3-musselman", "IRONMAN 70.3 Musselman", "Geneva", "NY", "half", "2026-07-12", "2027-07-11",
         "Seneca Lake, usually clear and around 72 F, which is wetsuit legal. Wind can whip it up: chop in 2025 pushed the DNF rate to about 22%.",
         "Rolling hills and flat stretches through farmland and along the water. The biggest climbs come near miles 30 and 35, and the last 20 miles are fast. Voted best 70.3 bike course in the 2024 athletes' choice awards.",
         "Two loops, mostly flat and shaded along the waterfront, with one large hill just outside town.",
         bikeTerrain="Rolling", runTerrain="Mostly flat"),
    race("ironman-70-3-new-mexico", "IRONMAN 70.3 New Mexico", "Ruidoso", "NM", "half", "2026-07-12", "2027-07-11",
         "Two loops in Grindstone Lake, a reservoir at about 7,000 ft. Water was about 72 F at the first race. Dock start with athletes going every few seconds.",
         "Two loops plus extra climbing. A fast descent from the lake, rolling highway miles, then a 2 to 3 mile climb back to transition. Officially about 1,300 ft of climbing; riders' GPS has read closer to 2,300 ft.",
         "Three loops with over 800 ft of short, punchy climbs around a municipal golf course on a paved path.",
         bikeGainFt=1300, runGainFt=800,
         weather="Racing at about 7,000 ft. Expect everything, especially the run, to feel harder than your sea level paces.",
         short="70.3 New Mexico"),
    race("ironman-70-3-oregon", "IRONMAN 70.3 Oregon", "Salem", "OR", "half", "2026-07-19", "2027-07-18",
         "Downstream swim in the Willamette River. The current usually helps, so the predictor takes 10% off your pace when course adjustments are on.",
         "Flat roads through the farmland around Salem.",
         "Flat course through the riverfront parks.",
         swimFactor=0.9, bikeTerrain="Flat", runTerrain="Flat"),
    race("ironman-70-3-ohio", "IRONMAN 70.3 Ohio", "Sandusky", "OH", "half", "2026-07-19", "2027-07-18",
         "A rare start: athletes jump from a ferry in Sandusky Bay and swim into the Lake Erie shoreline.",
         "Fast and flat through the farmland of Erie County.",
         "Through historic downtown Sandusky, including the renovated Columbus Avenue, to a loud downtown finish.",
         bikeTerrain="Flat"),
    race("ironman-70-3-boise", "IRONMAN 70.3 Boise", "Boise", "ID", "half", "2026-07-25", "2027-07-24",
         "One diamond-shaped loop in Lucky Peak Reservoir. Water has averaged about 72 F.",
         "One lap of rolling roads with about 1,567 ft of climbing.",
         "Two flat laps on the Boise River Greenbelt.",
         bikeGainFt=1567, runTerrain="Flat",
         weather="Average race day air temperature has been about 81 F."),
    race("ironman-70-3-maine", "IRONMAN 70.3 Maine", "Augusta", "ME", "half", "2026-07-26", "2027-07-25",
         "Swim in the Kennebec River.",
         "Through the hills of the Kennebec Valley.",
         "On the trails and streets of Augusta and central Maine.",
         bikeTerrain="Hilly"),
    race("ironman-70-3-louisville", "IRONMAN 70.3 Louisville", "Louisville", "KY", "half", "2026-08-16", None,
         "Swim in the Ohio River along the Louisville waterfront.",
         "Rolling roads in the Kentucky countryside outside the city.",
         "Through downtown Louisville.",
         bikeTerrain="Rolling"),
    race("ironman-70-3-northern-california", "IRONMAN 70.3 Northern California", "Redding", "CA", "half", "2026-08-16", "2027-05-23",
         "Whiskeytown Lake, starting at Oak Bottom.",
         "Point to point through Shasta County, ending at the Redding Civic Auditorium.",
         "Across the Sundial Bridge and along the Sacramento River Trail.",
         weather="The race moves from August in 2026 to May in 2027, which should mean cooler temperatures.",
         short="70.3 Northern California"),
    race("ironman-70-3-wisconsin", "IRONMAN 70.3 Wisconsin", "Madison", "WI", "half", "2026-09-12", None,
         "One lap in Lake Monona starting at Law Park Beach.",
         "One loop with about 1,744 ft of climbing.",
         "Very flat two-loop out and back with about 345 ft of climbing, finishing at the Capitol.",
         bikeGainFt=1744, runGainFt=345,
         weather="Held the day before IRONMAN Wisconsin, on the same weekend."),
    race("ironman-70-3-santa-cruz", "IRONMAN 70.3 Santa Cruz", "Santa Cruz", "CA", "half", "2026-09-13", None,
         "Ocean swim off Cowell Beach near the Santa Cruz Wharf. Cold Pacific water, so plan on a wetsuit.",
         "North on Highway 1 along the coast and back, with rolling climbs and coastal wind.",
         "Along West Cliff Drive and coastal trails, out and back, with some dirt sections.",
         bikeTerrain="Rolling", runTerrain="Rolling"),
    race("ironman-70-3-washington-tri-cities", "IRONMAN 70.3 Washington Tri-Cities", "Richland", "WA", "half", "2026-09-20", None,
         "Point to point, downriver in the Columbia River. The current usually helps, so the predictor takes 10% off your pace when course adjustments are on.",
         "One loop through wine country with about 1,800 ft of climbing.",
         "One flat out and back on paved riverside trails.",
         swimFactor=0.9, bikeGainFt=1800, runTerrain="Flat", short="70.3 Tri-Cities"),
    race("ironman-70-3-michigan", "IRONMAN 70.3 Michigan", "Frankfort", "MI", "half", "2026-09-20", None,
         "Betsie Bay, with water typically around 65 F.",
         "Flat rural roads inland from the Lake Michigan shore.",
         "Circles back around the bay with Lake Michigan views, finishing near Frankfort's pier and beach.",
         bikeTerrain="Flat",
         weather="Mid September on Lake Michigan can be cool. Bring layers for the morning."),
    race("ironman-70-3-new-york", "IRONMAN 70.3 New York", "Jones Beach", "NY", "half", "2026-09-26", None,
         "In Zachs Bay at Jones Beach. Can be choppy, with a push on the way back.",
         "Two loops on a wide parkway closed to traffic. Smooth, except a 2-mile concrete stretch with expansion joints. Crosswinds are strongest on the open stretches and bridges.",
         "Two flat loops along the beach and boardwalk.",
         bikeTerrain="Flat, windy", runTerrain="Flat", short="70.3 Jones Beach"),
    race("ironman-70-3-augusta", "IRONMAN 70.3 Augusta", "Augusta", "GA", "half", "2026-09-27", None,
         "A quick 1.2 miles downriver in the Savannah River. The current helps, so the predictor takes 10% off your pace when course adjustments are on.",
         "Through rural Augusta and the Georgia and South Carolina countryside.",
         "Flat and well shaded, along the North Augusta Greeneway trail and through downtown.",
         swimFactor=0.9, runTerrain="Flat",
         weather="Popular with first timers and with athletes chasing a personal best. Augusta has agreed to host for five more years."),
    race("ironman-70-3-waco", "IRONMAN 70.3 Waco", "Waco", "TX", "half", "2026-10-04", None,
         "In the Brazos River. After heavy rain the river can run high, and the swim has been cancelled for safety before.",
         "Mostly flat with good pavement and a few chip seal sections.",
         "Two loops in Cameron Park with steep hills you climb twice. About half the course is shaded.",
         bikeTerrain="Mostly flat", runTerrain="Hilly"),
    race("ironman-70-3-north-carolina", "IRONMAN 70.3 North Carolina", "Wilmington", "NC", "half", "2026-10-17", None,
         "Point to point in saltwater from Wrightsville Beach through Banks Channel. Tides vary by year, so the predictor uses your normal pace.",
         "Point to point from the beach into the countryside and back into Wilmington over the Isabel Holmes Bridge. Only about 643 ft of climbing.",
         "From downtown along Front Street to shaded Greenfield Lake and back, finishing across from Battleship North Carolina. About 261 ft of climbing.",
         bikeGainFt=643, runGainFt=261,
         weather="October weather is usually ideal, which makes this a favorite for first timers and personal bests."),
    race("ironman-70-3-indian-wells-la-quinta", "IRONMAN 70.3 Indian Wells-La Quinta", "La Quinta", "CA", "half", "2026-12-06", None,
         "Lake Cahuilla. December water has been cold (around 56 F at one recent race), so wetsuits are expected.",
         "Mostly flat desert roads, with a climb near the end that catches people off guard.",
         "Two loops with some hills. It can still be warm in the afternoon.",
         bikeTerrain="Mostly flat", runTerrain="Rolling", short="70.3 Indian Wells"),
    race("ironman-70-3-florida", "IRONMAN 70.3 Florida", "Haines City", "FL", "half", "2026-12-13", None,
         "Lake Eva, right next to Lake Eva Park.",
         "56 miles through the lakes and orange grove country of Polk County.",
         "Starts and finishes at Lake Eva Park in Haines City.",
         weather="One of the longest running 70.3 races in the US, celebrating 20 years in 2024."),

    # ---------------- Championship ----------------
    race("ironman-70-3-world-championship-2027", "IRONMAN 70.3 World Championship 2027", "Chattanooga", "TN", "half", None, "2027-08-28",
         "Based on the regular IRONMAN 70.3 Chattanooga course: " + CHATT_70_3_SWIM,
         "Based on the regular 70.3 Chattanooga course: " + CHATT_70_3_BIKE,
         "Based on the regular 70.3 Chattanooga course: " + CHATT_70_3_RUN,
         swimMi=1.4, swimFactor=0.9, bikeGainFt=2218, runGainFt=550,
         cutoffNote="The championship course and cutoffs have not been published yet. Cutoffs shown are the standard 70.3 limits (1:10 swim, 5:30 swim through bike, 8:30 total).",
         note="The 2027 IRONMAN 70.3 World Championship is in Chattanooga on August 28 and 29, 2027, with men and women racing on separate days. IRONMAN has described a Tennessee River swim, rolling bike into north Georgia, and a Riverwalk run. Until the championship course is published, this page uses the 2026 IRONMAN 70.3 Chattanooga course.",
         d2027_label="August 28 to 29, 2027",
         weather="Late August in Chattanooga is usually hot and humid. Check the wetsuit rule in the athlete guide closer to the race.",
         short="70.3 Worlds 2027"),
]

# Official IRONMAN race pages, taken from the "Register / Details" links on RaceCenter
# (October 2026). Races without a confirmed URL fall back to IRONMAN's race finder.
IRONMAN_FINDER = "https://www.ironman.com/races"
OFFICIAL = {
    "ironman-texas": "/im-texas", "ironman-jacksonville": "/races/im-jacksonville",
    "ironman-lake-placid": "/im-lake-placid", "ironman-wisconsin": "/races/im-wisconsin",
    "ironman-maryland": "/races/im-maryland", "ironman-chattanooga": "/im-chattanooga",
    "ironman-california": "/im-california", "ironman-florida": "/im-florida",
    "ironman-70-3-oceanside": "/im703-oceanside", "ironman-70-3-texas": "/im703-texas",
    "ironman-70-3-dallas-little-elm": "/races/im703-dallas-little-elm", "ironman-70-3-gulf-coast": "/races/im703-gulf-coast",
    "ironman-70-3-chattanooga": "/im703-chattanooga", "ironman-70-3-hawaii": "/im703-hawaii",
    "ironman-70-3-omaha": "/races/im703-omaha", "ironman-70-3-western-massachusetts": "/races/im703-western-massachusetts",
    "ironman-70-3-boulder": "/im703-boulder", "ironman-70-3-eagleman": "/im703-eagleman",
    "ironman-70-3-coeur-dalene": "/races/im703-coeur-dalene", "ironman-70-3-muncie": "/races/im703-muncie",
    "ironman-70-3-musselman": "/im703-musselman", "ironman-70-3-new-mexico": "/races/im703-ruidoso-new-mexico",
    "ironman-70-3-oregon": "/im703-oregon", "ironman-70-3-ohio": "/races/im703-ohio",
    "ironman-70-3-boise": "/im703-boise", "ironman-70-3-maine": "/races/im703-maine",
    "ironman-70-3-louisville": "/im703-louisville", "ironman-70-3-northern-california": "/races/im703-northern-california",
    "ironman-70-3-wisconsin": "/races/im703-wisconsin", "ironman-70-3-santa-cruz": "/im703-santa-cruz",
    "ironman-70-3-washington-tri-cities": "/races/im703-washington-tri-cities", "ironman-70-3-michigan": "/races/im703-michigan",
    "ironman-70-3-new-york": "/races/im703-new-york", "ironman-70-3-augusta": "/im703-augusta",
    "ironman-70-3-waco": "/im703-waco", "ironman-70-3-north-carolina": "/im703-north-carolina",
    "ironman-70-3-indian-wells-la-quinta": "/im703-indian-wells", "ironman-70-3-florida": "/im703-florida",
}
for _r in RACES:
    _p = OFFICIAL.get(_r["slug"])
    _r["official"] = "https://www.ironman.com" + _p if _p else IRONMAN_FINDER
    _r["officialExact"] = bool(_p)
